development:
  adapter: mysql2
  encoding: utf8
  database: library_system_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: library_system_test
  pool: 5
  username: root